### ISSUE TITLE
error after a new entry created

### ISSUE THREAD

**Issue by wangkezun** [Acidham/rsync-folders#1]
![image](https://user-images.githubusercontent.com/3012882/48816206-3ecab600-ed7c-11e8-9064-bf9fd772ce57.png)

**Comment by Acidham** [comment]
Can you try the following:

- open Console and type _Logger_ into the Search field?
- run rsync again
- cp log output

When you open logger and exec rsync you should see the file path to the wf cache dir. You can go there and delete rsync.txt file and try again. Note: With deleting rsync.txt you will loose your bookmarks.

**Comment by wangkezun** [comment]
do you mean open a terminal and exec Logger in it? I tried this way, and terminal showed nothing after I run rsync.

**Comment by Acidham** [comment]
No console, spotlight > console

**Comment by wangkezun** [comment]
sorry for the delay. I still don't get it.  Open spotlight and input console
![image](https://user-images.githubusercontent.com/3012882/49414380-23b16a80-f7ae-11e8-8bf6-fccc55e3c5f5.png)
what should I do next?

**Comment by wangkezun** [comment]
Done! Thanks. It looks like the config text was separated into two line. like this
```
11|config-name|local-dir
local-dir|remote-dir
```
after I delete the second line and make it like this 
```
11|config-name|local-dir|remote-dir
```
  it works.
