### ISSUE TITLE
seems not work in Catalina 10.15 (19A536g) ?

### ISSUE THREAD

**Issue by funabashi-cn-zz** [Acidham/rsync-folders#2]
My Alfred version is 4.0.3 (1092). After run 'rsync' and select 'New Entry', nothing happened.
please help me.
![729C6D77-0486-4851-AEC4-82CA7D91CDB9](https://user-images.githubusercontent.com/26640703/63567330-afb92b80-c5a3-11e9-8aff-dc5d876a766a.png)

**Comment by funabashi-cn-zz** [comment]
worked great . sorry for disturbed you...

**Comment by Acidham** [comment]
No you are right, the workflow is not upgraded to Alfred 4;) I assume you got a dialog asking you where to find the Application....?
